### ISSUE TITLE
[docs] add required docs to meet github community standards

### ISSUE THREAD

**Issue by davidlhw** [AfterClass-io/afterclass.io-v2#131]
see https://github.com/AfterClass-io/afterclass.io-v2/community

![image](https://github.com/AfterClass-io/afterclass.io-v2/assets/13061926/fecc820e-d58f-4810-91ee-cdd0db44f5ce)

**Comment by onebignick** [comment]
Can assign this to me

**Comment by davidlhw** [comment]
realized this would require more context, will be taking this on instead.

thanks for your help regardless! @onebignick
