### ISSUE TITLE
remove unused sidebar tabs

### ISSUE THREAD

**Issue by davidlhw** [AfterClass-io/afterclass.io-v2#172]
## Mockups / Screenshots

marketplace and deals are not planned to be worked on anytime soon. to reduce confusion from our users, we will remove these options from the sidebar

![image](https://github.com/AfterClass-io/afterclass.io-v2/assets/13061926/dc86adcb-ac97-4374-bc53-9393d5c231f2)

## Implementation

- remove unused sidebar items at [`src/common/components/Sidebar/Sidebar.tsx#L18-L42`](https://github.com/AfterClass-io/afterclass.io-v2/blob/main/src/common/components/Sidebar/Sidebar.tsx#L18-L42)

**Comment by ananyabhat29** [comment]
Hey @davidlhw I would like to work on this issue, please assign it to me.
