### ISSUE TITLE
[BUG] increasing review label tags upon switching between filters

### ISSUE THREAD

**Issue by Jaylin0312** [AfterClass-io/afterclass.io-v2#182]
## Describe the bug

https://github.com/AfterClass-io/afterclass.io-v2/assets/68802506/39425b5b-c2d1-49b4-8184-dc12b6246792

## To Reproduce
Steps to reproduce the behavior (refer to recording above):

1. Go to https://afterclass-io.vercel.app/course/COR-IS1702
2. Click on one professor filter
3. Uncheck the filter and check another professor filter
4. Repeat steps 2 and 3 for multiple times
5. Bug should be observed as shown in the recording

## Expected behavior

Labels should not be increasing, reviews should always look the same as shown here:

![image](https://github.com/AfterClass-io/afterclass.io-v2/assets/13061926/d31f4e22-e449-4902-ba6d-4206f634c64d)

**Comment by davidlhw** [comment]
closing this issue as it's not reproducible on both prod and latest main

we can re-open this if this surfaces again
