### ISSUE TITLE
update call to action buttons

### ISSUE THREAD

**Issue by davidlhw** [AfterClass-io/afterclass.io-v2#200]
### Current

![image](https://github.com/user-attachments/assets/dd623b32-b52a-4f2e-9a84-d056fb9bd0e5)

### To-be

![image](https://github.com/user-attachments/assets/27a5f0bd-de14-409f-847e-be2338fec218)

![image](https://github.com/user-attachments/assets/10211fed-d7c5-45fd-a206-613974be82ad)

### Required Changes

- github icon to OSS call to action button
- update edit icon color on write a review call to action button

**Comment by AlvinLingg** [comment]
Are we going to have the variant determine the type of icons that appear in the CTA component? Or do we pass in the icon(s) to be used as a prop (left and right icons)?

for example: Tertiary = Github icon, secondary/unspecified = Plus icon, in future some other variant = some default icon?

**Comment by davidlhw** [comment]
passing in icons as props seem to be better for decoupling
