### ISSUE TITLE
[Feat][UI] Course Page integration

### ISSUE THREAD

**Issue by davidlhw** [AfterClass-io/afterclass.io-v2#88]
## Mockups / Screenshots

https://www.figma.com/file/nSCkMgGjpXTgLFEHykk0yb/Product-Design?type=design&node-id=299-19281&mode=dev

### Authenticated

![image](https://github.com/AfterClass-io/afterclass.io-v2/assets/13061926/2ce080a3-e6bd-4eb7-9388-80e51f4ab96d)

### Unauthenticated

![image](https://github.com/AfterClass-io/afterclass.io-v2/assets/13061926/699e58ea-e9e3-4356-a2ab-e9b5494c73e4)

## Features

- all UX functionality should be working
    - filtering professor reviews
    - hidden sections when user is unauthenticated

**Comment by Jaylin0312** [comment]
first PR: https://github.com/AfterClass-io/afterclass.io-v2/pull/133
