### ISSUE TITLE
[Feat][UI] Layout sidebar

### ISSUE THREAD

**Issue by Aztriltus** [AfterClass-io/afterclass.io-v2#9]
## Mockups / Screenshots

![image](https://github.com/AfterClass-io/afterclass.io-v2/assets/6003064/97fce284-0f2c-4e7b-9fb6-19999e285381)

![image](https://github.com/AfterClass-io/afterclass.io-v2/assets/6003064/9cfd7fae-dd09-473c-82d2-cda2f46db630)

## Features

- Sidebar

### Core

Sidebar content
- Logo + afterclass text (can both be svg)
- Reusable sidebar item 
- Ignore input

### Optional

- `<Logo />` component with hideText, hideLogo props

## Implementation

`<Sidebar />`
- Use `<aside>`
- Use spacing utilities like `space-y-4` or `flex flex-col gap-4`. Should not use `mt-` or `mb-`
- Create an typed array to loop through and render the items

`<SidebarItem />`
- `active` prop for highlighting
- On hover, also show `active` style
- Accept `icon: ReactNode` and `label: string`
- Use colors from custom tailwind theme plugin `bg-gradient-tr from-element-secondary to-transparent`
- Accept `href` with `external: boolean` prop to either use `NextLink` for internal pages, or `a` for external (open as a new tab)

**Comment by jeromeandrewong** [comment]
done #18
